In [1]:
from pathlib import Path
import pandas as pd

data_path = Path("../data/credit_default.xls")

df = pd.read_excel(data_path, header=1)

print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

display(df.head())

Dataset shape: (30000, 25)

Column names:
['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default payment next month']

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

Check Data Quality

In [2]:
# 1. Check data types
print("DATA TYPES")
display(df.dtypes.to_frame(name="Data Type"))

# 2. Check missing values
print("MISSING VALUES")
missing = df.isnull().sum()

missing_summary = pd.DataFrame({
    "Missing Values": missing,
    "Missing Percentage": (missing / len(df) * 100).round(2)
})

display(missing_summary[missing_summary["Missing Values"] > 0])

# 3. Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# 4. Check duplicate customer IDs
print("Duplicate IDs:", df["ID"].duplicated().sum())

# 5. Check target distribution
target = "default payment next month"

print("TARGET DISTRIBUTION")
display(df[target].value_counts().sort_index().to_frame("Count"))

print("TARGET PERCENTAGE")
display(
    (df[target].value_counts(normalize=True).sort_index() * 100)
    .round(2)
    .to_frame("Percentage")
)

DATA TYPES

                           Data Type
ID                             int64
LIMIT_BAL                      int64
SEX                            int64
EDUCATION                      int64
MARRIAGE                       int64
AGE                            int64
PAY_0                          int64
PAY_2                          int64
PAY_3                          int64
PAY_4                          int64
PAY_5                          int64
PAY_6                          int64
BILL_AMT1                      int64
BILL_AMT2                      int64
BILL_AMT3                      int64
BILL_AMT4                      int64
BILL_AMT5                      int64
BILL_AMT6                      int64
PAY_AMT1                       int64
PAY_AMT2                       int64
PAY_AMT3                       int64
PAY_AMT4                       int64
PAY_AMT5                       int64
PAY_AMT6                       int64
default payment next month     int64

MISSING VALUES

Empty DataFrame
Columns: [Missing Values, Missing Percentage]
Index: []

Duplicate rows: 0
Duplicate IDs: 0
TARGET DISTRIBUTION

                            Count
default payment next month
0                           23364
1                            6636

TARGET PERCENTAGE

                            Percentage
default payment next month
0                                77.88
1                                22.12

Inspect the Numerical & Categrical Values

In [3]:
# Numerical summary
display(df.describe().T)

# Inspect coded categorical columns
categorical_columns = ["SEX", "EDUCATION", "MARRIAGE"]

for col in categorical_columns:
    print(f"\n{col} value counts:")
    display(df[col].value_counts(dropna=False).sort_index())

# Inspect repayment-status values
repayment_columns = ["PAY_0", "PAY_2", "PAY_3",
                     "PAY_4", "PAY_5", "PAY_6"]

for col in repayment_columns:
    print(f"\n{col} value counts:")
    display(df[col].value_counts(dropna=False).sort_index())

,count,mean,std,min,25%,50%,75%,max
ID,30000.0,15000.500000,8660.398374,1.0,7500.75,15000.5,22500.25,30000.0
LIMIT_BAL,30000.0,167484.322667,129747.661567,10000.0,50000.00,140000.0,240000.00,1000000.0
SEX,30000.0,1.603733,0.489129,1.0,1.00,2.0,2.00,2.0
EDUCATION,30000.0,1.853133,0.790349,0.0,1.00,2.0,2.00,6.0
MARRIAGE,30000.0,1.551867,0.521970,0.0,1.00,2.0,2.00,3.0
AGE,30000.0,35.485500,9.217904,21.0,28.00,34.0,41.00,79.0
PAY_0,30000.0,-0.016700,1.123802,-2.0,-1.00,0.0,0.00,8.0
PAY_2,30000.0,-0.133767,1.197186,-2.0,-1.00,0.0,0.00,8.0
PAY_3,30000.0,-0.166200,1.196868,-2.0,-1.00,0.0,0.00,8.0
PAY_4,30000.0,-0.220667,1.169139,-2.0,-1.00,0.0,0.00,8.0
PAY_5,30000.0,-0.266200,1.133187,-2.0,-1.00,0.0,0.00,8.0
PAY_6,30000.0,-0.291100,1.149988,-2.0,-1.00,0.0,0.00,8.0
BILL_AMT1,30000.0,51223.330900,73635.860576,-165580.0,3558.75,22381.5,67091.00,964511.0
BILL_AMT2,30000.0,49179.075167,71173.768783,-69777.0,2984.75,21200.0,64006.25,983931.0
BILL_AMT3,30000.0,47013.154800,69349.387427,-157264.0,2666.25,20088.5,60164.75,1664089.0
BILL_AMT4,30000.0,43262.948967,64332.856134,-170000.0,2326.75,19052.0,54506.00,891586.0
BILL_AMT5,30000.0,40311.400967,60797.155770,-81334.0,1763.00,18104.5,50190.50,927171.0
BILL_AMT6,30000.0,38871.760400,59554.107537,-339603.0,1256.00,17071.0,49198.25,961664.0
PAY_AMT1,30000.0,5663.580500,16563.280354,0.0,1000.00,2100.0,5006.00,873552.0
PAY_AMT2,30000.0,5921.163500,23040.870402,0.0,833.00,2009.0,5000.00,1684259.0
PAY_AMT3,30000.0,5225.681500,17606.961470,0.0,390.00,1800.0,4505.00,896040.0
PAY_AMT4,30000.0,4826.076867,15666.159744,0.0,296.00,1500.0,4013.25,621000.0
PAY_AMT5,30000.0,4799.387633,15278.305679,0.0,252.50,1500.0,4031.50,426529.0
PAY_AMT6,30000.0,5215.502567,17777.465775,0.0,117.75,1500.0,4000.00,528666.0
default payment next month,30000.0,0.221200,0.415062,0.0,0.00,0.0,0.00,1.0

SEX value counts:

SEX
1    11888
2    18112
Name: count, dtype: int64

EDUCATION value counts:

EDUCATION
0       14
1    10585
2    14030
3     4917
4      123
5      280
6       51
Name: count, dtype: int64

MARRIAGE value counts:

MARRIAGE
0       54
1    13659
2    15964
3      323
Name: count, dtype: int64

PAY_0 value counts:

PAY_0
-2     2759
-1     5686
 0    14737
 1     3688
 2     2667
 3      322
 4       76
 5       26
 6       11
 7        9
 8       19
Name: count, dtype: int64

PAY_2 value counts:

PAY_2
-2     3782
-1     6050
 0    15730
 1       28
 2     3927
 3      326
 4       99
 5       25
 6       12
 7       20
 8        1
Name: count, dtype: int64

PAY_3 value counts:

PAY_3
-2     4085
-1     5938
 0    15764
 1        4
 2     3819
 3      240
 4       76
 5       21
 6       23
 7       27
 8        3
Name: count, dtype: int64

PAY_4 value counts:

PAY_4
-2     4348
-1     5687
 0    16455
 1        2
 2     3159
 3      180
 4       69
 5       35
 6        5
 7       58
 8        2
Name: count, dtype: int64

PAY_5 value counts:

PAY_5
-2     4546
-1     5539
 0    16947
 2     2626
 3      178
 4       84
 5       17
 6        4
 7       58
 8        1
Name: count, dtype: int64

PAY_6 value counts:

PAY_6
-2     4895
-1     5740
 0    16286
 2     2766
 3      184
 4       49
 5       13
 6       19
 7       46
 8        2
Name: count, dtype: int64

Check Re Payment and SEX column

In [4]:
# Inspect SEX
print("SEX value counts:")
display(df["SEX"].value_counts(dropna=False).sort_index())

# Inspect repayment status
repayment_columns = [
    "PAY_0", "PAY_2", "PAY_3",
    "PAY_4", "PAY_5", "PAY_6"
]

for col in repayment_columns:
    print(f"\n{col} value counts:")
    display(df[col].value_counts(dropna=False).sort_index())

SEX value counts:

SEX
1    11888
2    18112
Name: count, dtype: int64

PAY_0 value counts:

PAY_0
-2     2759
-1     5686
 0    14737
 1     3688
 2     2667
 3      322
 4       76
 5       26
 6       11
 7        9
 8       19
Name: count, dtype: int64

PAY_2 value counts:

PAY_2
-2     3782
-1     6050
 0    15730
 1       28
 2     3927
 3      326
 4       99
 5       25
 6       12
 7       20
 8        1
Name: count, dtype: int64

PAY_3 value counts:

PAY_3
-2     4085
-1     5938
 0    15764
 1        4
 2     3819
 3      240
 4       76
 5       21
 6       23
 7       27
 8        3
Name: count, dtype: int64

PAY_4 value counts:

PAY_4
-2     4348
-1     5687
 0    16455
 1        2
 2     3159
 3      180
 4       69
 5       35
 6        5
 7       58
 8        2
Name: count, dtype: int64

PAY_5 value counts:

PAY_5
-2     4546
-1     5539
 0    16947
 2     2626
 3      178
 4       84
 5       17
 6        4
 7       58
 8        1
Name: count, dtype: int64

PAY_6 value counts:

PAY_6
-2     4895
-1     5740
 0    16286
 2     2766
 3      184
 4       49
 5       13
 6       19
 7       46
 8        2
Name: count, dtype: int64

In [5]:
import pandas as pd
import numpy as np
from pathlib import Path

# Work on a copy; keep the original df unchanged
df_clean = df.copy()

target = "default payment next month"

# Remove the customer identifier from model features later,
# but keep it in this working dataset for traceability.
print("Original shape:", df_clean.shape)
print("Missing values:", df_clean.isna().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())
print("Duplicate IDs:", df_clean["ID"].duplicated().sum())

# Validate the target
print("Target values:", sorted(df_clean[target].unique()))
assert set(df_clean[target].unique()).issubset({0, 1})
assert df_clean["ID"].is_unique
assert df_clean[target].notna().all()

Original shape: (30000, 25)
Missing values: 0
Duplicate rows: 0
Duplicate IDs: 0
Target values: [np.int64(0), np.int64(1)]

Handle Category Codes

In [6]:
# Work on copies of the original category values
df_clean["EDUCATION"] = df_clean["EDUCATION"].replace({
    0: 4,
    5: 4,
    6: 4
})

df_clean["MARRIAGE"] = df_clean["MARRIAGE"].replace({
    0: 3
})

print("EDUCATION after recoding:")
display(df_clean["EDUCATION"].value_counts().sort_index())

print("MARRIAGE after recoding:")
display(df_clean["MARRIAGE"].value_counts().sort_index())

EDUCATION after recoding:

EDUCATION
1    10585
2    14030
3     4917
4      468
Name: count, dtype: int64

MARRIAGE after recoding:

MARRIAGE
1    13659
2    15964
3      377
Name: count, dtype: int64

Engineering Financial Features

In [7]:
# 1. Count months with a recorded payment delay
pay_cols = ["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]

df_clean["delayed_months"] = (df_clean[pay_cols] > 0).sum(axis=1)

# 2. Maximum recorded positive delay
df_clean["max_payment_delay"] = df_clean[pay_cols].clip(lower=0).max(axis=1)

# 3. Average bill amount over six months
bill_cols = [
    "BILL_AMT1", "BILL_AMT2", "BILL_AMT3",
    "BILL_AMT4", "BILL_AMT5", "BILL_AMT6"
]
df_clean["avg_bill_amount"] = df_clean[bill_cols].mean(axis=1)

# 4. Average payment amount over six months
payment_cols = [
    "PAY_AMT1", "PAY_AMT2", "PAY_AMT3",
    "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"
]
df_clean["avg_payment_amount"] = df_clean[payment_cols].mean(axis=1)

# 5. Total payments over six months
df_clean["total_payment_amount"] = df_clean[payment_cols].sum(axis=1)

# 6. Recent bill relative to the granted credit limit
df_clean["recent_bill_to_limit_ratio"] = (
    df_clean["BILL_AMT1"] / df_clean["LIMIT_BAL"].replace(0, np.nan)
)

# 7. Recent payment relative to the absolute bill amount
df_clean["recent_payment_to_bill_ratio"] = (
    df_clean["PAY_AMT1"] / (df_clean["BILL_AMT1"].abs() + 1)
)

# Inspect the engineered features
new_features = [
    "delayed_months",
    "max_payment_delay",
    "avg_bill_amount",
    "avg_payment_amount",
    "total_payment_amount",
    "recent_bill_to_limit_ratio",
    "recent_payment_to_bill_ratio"
]

display(df_clean[new_features].describe().T)

,count,mean,std,min,25%,50%,75%,max
delayed_months,30000.0,0.834200,1.554303,0.000000,0.000000,0.000000,1.000000,6.000000e+00
max_payment_delay,30000.0,0.682200,1.073518,0.000000,0.000000,0.000000,2.000000,8.000000e+00
avg_bill_amount,30000.0,44976.945200,63260.721860,-56043.166667,4781.333333,21051.833333,57104.416667,8.773138e+05
avg_payment_amount,30000.0,5275.232094,10137.946323,0.000000,1113.291667,2397.166667,5583.916667,6.273443e+05
total_payment_amount,30000.0,31651.392567,60827.677939,0.000000,6679.750000,14383.000000,33503.500000,3.764066e+06
recent_bill_to_limit_ratio,30000.0,0.423771,0.411462,-0.619892,0.022032,0.313994,0.829843,6.455300e+00
recent_payment_to_bill_ratio,30000.0,99.128560,2692.818701,0.000000,0.035244,0.057385,0.294092,2.988870e+05

Check New Features

In [8]:
# Check engineered-feature quality
feature_check = pd.DataFrame({
    "Missing": df_clean[new_features].isna().sum(),
    "Unique Values": df_clean[new_features].nunique(),
    "Minimum": df_clean[new_features].min(),
    "Maximum": df_clean[new_features].max()
})

display(feature_check)

# Compare feature averages by target class
print("Feature averages by default outcome:")
display(
    df_clean.groupby(target)[new_features]
    .mean()
    .round(3)
    .T
)

# Default rate by number of delayed months
print("Default rate by delayed months:")
display(
    df_clean.groupby("delayed_months")[target]
    .agg(["count", "mean"])
    .rename(columns={"mean": "default_rate"})
    .assign(default_rate=lambda x: (x["default_rate"] * 100).round(2))
)

,Missing,Unique Values,Minimum,Maximum
delayed_months,0,7,0.000000,6.000000e+00
max_payment_delay,0,9,0.000000,8.000000e+00
avg_bill_amount,0,27370,-56043.166667,8.773138e+05
avg_payment_amount,0,19180,0.000000,6.273443e+05
total_payment_amount,0,19180,0.000000,3.764066e+06
recent_bill_to_limit_ratio,0,25565,-0.619892,6.455300e+00
recent_payment_to_bill_ratio,0,24007,0.000000,2.988870e+05

Feature averages by default outcome:

default payment next month            0          1
delayed_months                    0.504      1.996
max_payment_delay                 0.470      1.428
avg_bill_amount               45404.818  43470.493
avg_payment_amount             5828.237   3328.216
total_payment_amount          34969.421  19969.294
recent_bill_to_limit_ratio        0.405      0.490
recent_payment_to_bill_ratio    109.103     64.012

Default rate by delayed months:

                count  default_rate
delayed_months
0               19931         11.71
1                4426         29.82
2                1899         38.76
3                1154         50.87
4                 951         57.31
5                 298         57.38
6                1341         70.32

Save Processed Dataset Summary

In [12]:
# Adjust this path if your notebook has a different working directory
data_dir = Path("week-02-loan-default-risk/data")
reports_dir = Path("week-02-loan-default-risk/reports")

data_dir.mkdir(parents=True, exist_ok=True)
reports_dir.mkdir(parents=True, exist_ok=True)

# Save processed data
processed_path = data_dir / "processed_credit_default.csv"
df_clean.to_csv(processed_path, index=False)

# Save a compact feature summary
summary_path = reports_dir / "day01_feature_summary.csv"

df_clean[new_features].describe().T.to_csv(summary_path)

print("Processed dataset saved to:", processed_path.resolve())
print("Feature summary saved to:", summary_path.resolve())
print("Processed dataset shape:", df_clean.shape)

Processed dataset saved to: C:\Users\hadia_nxqa311\ai_engineering_journey\week-02-loan-default-risk\notebooks\week-02-loan-default-risk\data\processed_credit_default.csv
Feature summary saved to: C:\Users\hadia_nxqa311\ai_engineering_journey\week-02-loan-default-risk\notebooks\week-02-loan-default-risk\reports\day01_feature_summary.csv
Processed dataset shape: (30000, 32)